[package]
name = "motifence"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.3", features = ["derive"] }
bio = "1.6.0"
regex = "1.10.4"
flate2 = "1.0.28"
